// frontend/app/web-react/views/Home.tsx
import { Button, Card, Typography } from '@douyinfe/semi-ui-19';
import {
  IconApps,
  IconClock,
  IconLink,
  IconPlus,
  IconTickCircle,
  IconUpload,
} from '@douyinfe/semi-icons';
import { useNavigate } from 'react-router';
import { PERMISSIONS } from '@shared/types/auth';
import { useAuthStore } from '../stores/auth';
import { isMigrated } from '../routes/migration';

const { Title, Text } = Typography;

const STATS = [
  { key: 'applications', label: '应用总数', icon: <IconApps /> },
  { key: 'pending', label: '待发布', icon: <IconClock /> },
  { key: 'released', label: '已发布', icon: <IconTickCircle /> },
];

const QUICK_ACTIONS = [
  {
    path: '/application/apply',
    label: '申请应用',
    icon: <IconPlus />,
    permission: PERMISSIONS.APPLICATIONS_WRITE,
  },
  {
    path: '/publish/merge',
    label: '代码合并',
    icon: <IconLink />,
    permission: PERMISSIONS.RELEASES_CREATE,
  },
  {
    path: '/publish/deploy',
    label: '服务发布',
    icon: <IconUpload />,
    permission: PERMISSIONS.RELEASES_READ,
  },
];

export default function Home() {
  const navigate = useNavigate();
  const permissions = useAuthStore(state => state.user?.permissions) || [];
  const can = (permission: string) => (permissions as string[]).includes(permission);

  return (
    <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
      <Card style={{ flex: '1 1 280px', minHeight: 280 }} title='欢迎使用'>
        <div style={{ textAlign: 'center', paddingTop: 32 }}>
          <Title heading={3} className='welcome-title'>
            Ares
          </Title>
          <Text type='tertiary'>一站式应用发布管理平台</Text>
        </div>
      </Card>

      <Card style={{ flex: '1 1 280px', minHeight: 280 }} title='应用统计'>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 18, paddingTop: 16 }}>
          {STATS.map(stat => (
            <div
              key={stat.key}
              style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}
            >
              <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                {stat.icon}
                {stat.label}
              </span>
              {/* The Vue page renders the same placeholder counters; no API backs them yet. */}
              <Text strong>0</Text>
            </div>
          ))}
        </div>
      </Card>

      <Card style={{ flex: '1 1 280px', minHeight: 280 }} title='快捷操作'>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12, paddingTop: 16 }}>
          {QUICK_ACTIONS.filter(action => can(action.permission)).map(action => (
            <Button
              key={action.path}
              theme='light'
              icon={action.icon}
              disabled={!isMigrated(action.path)}
              onClick={() => navigate(action.path)}
            >
              {action.label}
            </Button>
          ))}
        </div>
      </Card>
    </div>
  );
}

// frontend/app/web/views/Home.vue
<template>
  <div class="home-wrapper">
    <el-row :gutter="20">
      <!-- 欢迎卡片 -->
      <el-col :span="8">
        <el-card class="home-card">
          <template #header>
            <span>欢迎使用</span>
          </template>
          <div class="welcome-content card-content">
            <el-icon class="welcome-icon"><Promotion /></el-icon>
            <div class="welcome-title">Ares</div>
            <div class="welcome-desc">一站式应用发布管理平台</div>
          </div>
        </el-card>
      </el-col>
      <!-- 应用统计卡片 -->
      <el-col :span="8">
        <el-card class="home-card">
          <template #header>
            <span>应用统计</span>
          </template>
          <div class="stats-list card-content">
            <div class="stats-item">
              <el-icon class="stats-icon"><Files /></el-icon>
              <span>应用总数</span>
              <span class="stats-value">0</span>
            </div>
            <div class="stats-item">
              <el-icon class="stats-icon"><Clock /></el-icon>
              <span>待发布</span>
              <span class="stats-value">0</span>
            </div>
            <div class="stats-item">
              <el-icon class="stats-icon"><Finished /></el-icon>
              <span>已发布</span>
              <span class="stats-value">0</span>
            </div>
          </div>
        </el-card>
      </el-col>
      <!-- 快捷操作卡片 -->
      <el-col :span="8">
        <el-card class="home-card">
          <template #header>
            <span>快捷操作</span>
          </template>
          <div class="quick-actions card-content">
            <el-button
              v-if="authStore.can(PERMISSIONS.APPLICATIONS_WRITE)"
              type="primary"
              size="large"
              class="quick-btn"
              @click="goApply"
              plain
            >
              <el-icon><Plus /></el-icon><span>申请应用</span>
            </el-button>
            <el-button
              v-if="authStore.can(PERMISSIONS.RELEASES_CREATE)"
              type="success"
              size="large"
              class="quick-btn"
              @click="goMerge"
              plain
            >
              <el-icon><Link /></el-icon><span>代码合并</span>
            </el-button>
            <el-button
              v-if="authStore.can(PERMISSIONS.RELEASES_READ)"
              type="warning"
              size="large"
              class="quick-btn"
              @click="goDeploy"
              plain
            >
              <el-icon><UploadFilled /></el-icon><span>服务发布</span>
            </el-button>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import {
  Promotion,
  Files,
  Clock,
  Finished,
  Plus,
  Link,
  UploadFilled,
} from '@element-plus/icons-vue';
import { useAuthStore } from '@/stores/auth';
import { PERMISSIONS } from '@shared/types/auth';

const router = useRouter();
const authStore = useAuthStore();
const goApply = () => router.push('/application/apply');
const goMerge = () => router.push('/publish/merge');
const goDeploy = () => router.push('/publish/deploy');
</script>

<style scoped>
.home-wrapper {
  background: #f5f7fa;
  min-height: 100%;
}
.el-card {
  border-radius: 8px;
}
.home-card {
  height: 280px;
  display: flex;
  flex-direction: column;
}
.card-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
}
.welcome-content {
  text-align: center;
}
.welcome-title {
  font-size: 2rem;
  font-weight: bold;
  margin-bottom: 12px;
}
.welcome-desc {
  color: #909399;
}
.welcome-icon {
  font-size: 40px;
  color: #409eff;
  margin-bottom: 12px;
}
.stats-list {
  display: flex;
  flex-direction: column;
  gap: 18px;
  padding: 16px 0;
}
.stats-item {
  display: flex;
  align-items: center;
  font-size: 16px;
  color: #606266;
}
.stats-icon {
  font-size: 22px;
  margin-right: 8px;
  color: #409eff;
}
.stats-value {
  margin-left: auto;
  font-weight: bold;
  color: #409eff;
  font-size: 18px;
}
.quick-actions {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 16px 0;
  align-items: stretch;
}
.quick-btn {
  margin: 0;
  font-size: 16px;
  display: flex;
  align-items: center;
  gap: 6px;
  width: 100%;
  justify-content: center;
  box-sizing: border-box;
}
.quick-btn :deep(.el-button__icon) {
  margin-left: 0 !important;
  margin-right: 8px !important;
}
</style>
