// frontend/app/web-react/views/NotFound.tsx
import { Button, Empty } from '@douyinfe/semi-ui-19';
import { useNavigate } from 'react-router';

export default function NotFound() {
  const navigate = useNavigate();
  return (
    <Empty title='页面不存在' description='请检查地址，或返回首页。' style={{ padding: 48 }}>
      <Button theme='solid' type='primary' onClick={() => navigate('/', { replace: true })}>
        返回首页
      </Button>
    </Empty>
  );
}

// frontend/app/web/views/NotFound.vue
<template>
  <el-result icon="warning" title="页面不存在" sub-title="请检查地址后重试。">
    <template #extra>
      <el-button type="primary" @click="router.replace('/')">返回首页</el-button>
    </template>
  </el-result>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';

const router = useRouter();
</script>
